CREATE TABLE CASE_TBL (
  i integer,
  f double precision
);

CREATE TABLE CASE2_TBL (
  i integer,
  j integer
);

INSERT INTO CASE_TBL VALUES (1, 10.1);
INSERT INTO CASE_TBL VALUES (2, 20.2);
INSERT INTO CASE_TBL VALUES (3, -30.3);
INSERT INTO CASE_TBL VALUES (4, NULL);

INSERT INTO CASE2_TBL VALUES (1, -1);
INSERT INTO CASE2_TBL VALUES (2, -2);
INSERT INTO CASE2_TBL VALUES (3, -3);
INSERT INTO CASE2_TBL VALUES (2, -4);
INSERT INTO CASE2_TBL VALUES (1, NULL);
INSERT INTO CASE2_TBL VALUES (NULL, -6);


SELECT CASE WHEN i=1 THEN 2 ELSE 3 END as t FROM CASE_TBL;

SELECT i, CASE i WHEN 2 THEN 20 when 3 then 30 ELSE 40 END FROM CASE_TBL;

UPDATE CASE_TBL
 SET i = CASE WHEN i >= 3 THEN (-i)
               ELSE (2 * i) END;
               
SELECT i, -i, f, -f FROM CASE_TBL;

select nullif(i,2) from case_tbl;

SELECT  *    
  FROM CASE_TBL a, CASE2_TBL b
  WHERE COALESCE(f,b.i) = 2;

