#!/bin/sh
# Source validation pre-commit hook
#
# This script collects all modified files and runs it through our source code
# validation script. The validation script returns 0 on success and 1 on any
# failure.
#
# To enable, symlink this file to '.git/hooks/pre-commit' like so:
#   ln -s ../../script/git-hooks/pre-commit .git/hooks/pre-commit

files=$(git diff --name-only HEAD --cached --diff-filter=d | grep '\.\(cpp\|h\)$')
if [ -n "$files" ]; then
  python script/validators/source_validator.py --files $files
  result=$?
  if [ $result -ne 0 ]; then
    echo "Use './script/formatter/formatter.py -c -f' to format all staged files or '--no-verify' to temporarily bypass the pre-commit hook. Be aware that changed files have to be staged again!"
  fi
  exit $result
fi

exit 0
