################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/tutorial \
src/tools/ifaddrs \
src/tools/findoidjoins \
src/tools/entab \
src/timezone \
src/test/thread \
src/test/regress \
src/test/modules/worker_spi \
src/test/modules/test_shm_mq \
src/test/modules/test_parser \
src/test/modules/dummy_seclabel \
src/test/locale \
src/test/isolation \
src/test/examples \
src/port \
src/pl/plpython \
src/pl/plpgsql/src \
src/pl/plperl \
src/interfaces/libpq \
src/interfaces/libpq/test \
src/interfaces/ecpg/test \
src/interfaces/ecpg/test/expected \
src/interfaces/ecpg/preproc \
src/interfaces/ecpg/pgtypeslib \
src/interfaces/ecpg/ecpglib \
src/interfaces/ecpg/compatlib \
src/common \
src/bin/scripts \
src/bin/psql \
src/bin/pgevent \
src/bin/pg_resetxlog \
src/bin/pg_dump \
src/bin/pg_ctl \
src/bin/pg_controldata \
src/bin/pg_config \
src/bin/pg_basebackup \
src/bin/initdb \
src/backend/utils/time \
src/backend/utils/sort \
src/backend/utils/resowner \
src/backend/utils/mmgr \
src/backend/utils/misc \
src/backend/utils/mb \
src/backend/utils/mb/conversion_procs/utf8_and_win \
src/backend/utils/mb/conversion_procs/utf8_and_uhc \
src/backend/utils/mb/conversion_procs/utf8_and_sjis2004 \
src/backend/utils/mb/conversion_procs/utf8_and_sjis \
src/backend/utils/mb/conversion_procs/utf8_and_johab \
src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1 \
src/backend/utils/mb/conversion_procs/utf8_and_iso8859 \
src/backend/utils/mb/conversion_procs/utf8_and_gbk \
src/backend/utils/mb/conversion_procs/utf8_and_gb18030 \
src/backend/utils/mb/conversion_procs/utf8_and_euc_tw \
src/backend/utils/mb/conversion_procs/utf8_and_euc_kr \
src/backend/utils/mb/conversion_procs/utf8_and_euc_jp \
src/backend/utils/mb/conversion_procs/utf8_and_euc_cn \
src/backend/utils/mb/conversion_procs/utf8_and_euc2004 \
src/backend/utils/mb/conversion_procs/utf8_and_cyrillic \
src/backend/utils/mb/conversion_procs/utf8_and_big5 \
src/backend/utils/mb/conversion_procs/utf8_and_ascii \
src/backend/utils/mb/conversion_procs/latin_and_mic \
src/backend/utils/mb/conversion_procs/latin2_and_win1250 \
src/backend/utils/mb/conversion_procs/euc_tw_and_big5 \
src/backend/utils/mb/conversion_procs/euc_kr_and_mic \
src/backend/utils/mb/conversion_procs/euc_jp_and_sjis \
src/backend/utils/mb/conversion_procs/euc_cn_and_mic \
src/backend/utils/mb/conversion_procs/euc2004_sjis2004 \
src/backend/utils/mb/conversion_procs/cyrillic_and_mic \
src/backend/utils/mb/conversion_procs/ascii_and_mic \
src/backend/utils/init \
src/backend/utils/hash \
src/backend/utils \
src/backend/utils/fmgr \
src/backend/utils/error \
src/backend/utils/cache \
src/backend/utils/adt \
src/backend/tsearch \
src/backend/tcop \
src/backend/storage/smgr \
src/backend/storage/page \
src/backend/storage/lmgr \
src/backend/storage/large_object \
src/backend/storage/ipc \
src/backend/storage/freespace \
src/backend/storage/file \
src/backend/storage/buffer \
src/backend/snowball \
src/backend/snowball/libstemmer \
src/backend/rewrite \
src/backend/replication \
src/backend/replication/logical \
src/backend/replication/libpqwalreceiver \
src/backend/regex \
src/backend/postmaster \
src/backend/port \
src/backend/port/win32 \
src/backend/port/dynloader \
src/backend/port/darwin \
src/backend/parser \
src/backend/optimizer/util \
src/backend/optimizer/prep \
src/backend/optimizer/plan \
src/backend/optimizer/path \
src/backend/optimizer/geqo \
src/backend/nodes \
src/backend/main \
src/backend/libpq \
src/backend/lib \
src/backend/foreign \
src/backend/executor \
src/backend/commands \
src/backend/catalog \
src/backend/bootstrap \
src/backend/access/transam \
src/backend/access/spgist \
src/backend/access/rmgrdesc \
src/backend/access/nbtree \
src/backend/access/index \
src/backend/access/heap \
src/backend/access/hash \
src/backend/access/gist \
src/backend/access/gin \
src/backend/access/common \
src/backend/access/brin \
contrib/xml2 \
contrib/vacuumlo \
contrib/uuid-ossp \
contrib/unaccent \
contrib/tsearch2 \
contrib/test_decoding \
contrib/tcn \
contrib/tablefunc \
contrib/sslinfo \
contrib/spi \
contrib/sepgsql \
contrib/seg \
contrib/postgres_fdw \
contrib/pgstattuple \
contrib/pgrowlocks \
contrib/pgcrypto \
contrib/pgbench \
contrib/pg_xlogdump \
contrib/pg_upgrade_support \
contrib/pg_upgrade \
contrib/pg_trgm \
contrib/pg_test_timing \
contrib/pg_test_fsync \
contrib/pg_stat_statements \
contrib/pg_standby \
contrib/pg_prewarm \
contrib/pg_freespacemap \
contrib/pg_buffercache \
contrib/pg_archivecleanup \
contrib/passwordcheck \
contrib/pageinspect \
contrib/oid2name \
contrib/ltree \
contrib/lo \
contrib/isn \
contrib/intarray \
contrib/hstore \
contrib/fuzzystrmatch \
contrib/file_fdw \
contrib/earthdistance \
contrib/dict_xsyn \
contrib/dict_int \
contrib/dblink \
contrib/cube \
contrib/citext \
contrib/chkpass \
contrib/btree_gist \
contrib/btree_gin \
contrib/auto_explain \
contrib/auth_delay \
contrib/adminpack \
citus/postgres_vectorization_test \

