# Dockerfile specifically for build testing from Jenkins
FROM centos:7

ADD . /peloton
RUN yum -q -y install sudo wget clang

RUN /bin/bash -c "source ./peloton/script/installation/packages.sh"

RUN echo -n "Peloton Debug build with "; g++ --version | head -1
RUN mkdir /peloton/build && cd /peloton/build && cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=False .. && make -j4 && make install

RUN echo -n "Peloton Release build with "; g++ --version | head -1
RUN rm -rf /peloton/build && mkdir /peloton/build && cd /peloton/build && cmake -DCMAKE_BUILD_TYPE=Release -DCOVERALLS=False .. && make -j4 && make install

RUN echo -n "Peloton Debug build with "; clang++ --version | head -1
RUN rm -rf /peloton/build && mkdir /peloton/build && cd /peloton/build && CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=False .. && make -j4 && make install

RUN echo -n "Peloton Release build with "; clang++ --version | head -1
RUN rm -rf /peloton/build && mkdir /peloton/build && cd /peloton/build && CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCOVERALLS=False .. && make -j4 && make install
