# -*- mode: ruby -*-
# vi: set ft=ruby et:

# Customize VM resources
VM_CPUS = "4"
VM_MEMORY = "2048" # MB
VM_NAME = "PelotonVM"

Vagrant.configure(2) do |config|

  # Pick a box to use
  config.vm.box = "ubuntu/trusty64"

  # Config VM
  config.vm.provider :virtualbox do |vb|
    vb.customize [ "modifyvm", :id,
      "--memory", VM_MEMORY,
      "--name", VM_NAME,
      "--nicspeed1", 1000000,
      "--nicspeed2", 1000000,
      "--ioapic", "on",
      "--cpus", VM_CPUS ]

    # Enable SSE 4.2
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]

    # Enable AVX2
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/IsaExts/AVX2", "1"]
  end

  # SSH
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # Setup environment
  config.vm.provision :shell, :inline => "apt-get update"
  config.vm.provision "shell", :path => "https://raw.githubusercontent.com/cmu-db/peloton/master/script/installation/packages.sh"
  config.vm.provision "shell", :path => "https://raw.githubusercontent.com/cmu-db/peloton/master/script/installation/vagrant-customize.sh", :privileged => false

  # Link current repo into VM
  config.vm.synced_folder "../..", "/peloton"

  end
