DROP TABLE IF EXISTS foo;
CREATE TABLE foo (val TIMESTAMP NOT NULL);
INSERT INTO foo VALUES ('2017-01-02 12:13:14.999999+00');
INSERT INTO foo VALUES ('2028-08-18 03:44:55.666666+00');

SELECT EXTRACT(CENTURY FROM val) AS century FROM foo ORDER BY val;
SELECT EXTRACT(DAY FROM val) AS day FROM foo ORDER BY val;
SELECT EXTRACT(DECADE FROM val) AS decade FROM foo ORDER BY val;
SELECT EXTRACT(DOW FROM val) AS dow FROM foo ORDER BY val;
SELECT EXTRACT(DOY FROM val) AS doy FROM foo ORDER BY val;
SELECT EXTRACT(HOUR FROM val) AS hour FROM foo ORDER BY val;
SELECT EXTRACT(MICROSECOND FROM val) AS microsecond FROM foo ORDER BY val;
SELECT EXTRACT(MILLENNIUM FROM val) AS millennium FROM foo ORDER BY val;
SELECT EXTRACT(MILLISECOND FROM val) AS millisecond FROM foo ORDER BY val;
SELECT EXTRACT(MINUTE FROM val) AS minute FROM foo ORDER BY val;
SELECT EXTRACT(MINUTES FROM val) AS minutes FROM foo ORDER BY val;
SELECT EXTRACT(MONTH FROM val) AS month FROM foo ORDER BY val;
SELECT EXTRACT(MONTHS FROM val) AS months FROM foo ORDER BY val;
SELECT EXTRACT(QUARTER FROM val) AS quarter FROM foo ORDER BY val;
SELECT EXTRACT(SECOND FROM val) AS second FROM foo ORDER BY val;
SELECT EXTRACT(SECONDS FROM val) AS seconds FROM foo ORDER BY val;
SELECT EXTRACT(WEEK FROM val) AS week FROM foo ORDER BY val;
SELECT EXTRACT(YEAR FROM val) AS year FROM foo ORDER BY val;

SELECT COUNT(*) FROM foo WHERE EXTRACT(YEAR FROM val) = 2028;
