DROP TABLE IF EXISTS foo;
CREATE TABLE foo (id INT PRIMARY KEY, val VARCHAR(32) DEFAULT NULL);

INSERT INTO foo VALUES (0, 'Cappadonna');
INSERT INTO foo VALUES (1, 'Ghostface Killah');
INSERT INTO foo VALUES (2, 'GZA');
INSERT INTO foo VALUES (3, 'Inspectah Deck');
INSERT INTO foo VALUES (4, 'Masta Killa');
INSERT INTO foo VALUES (5, 'Method Man');
INSERT INTO foo VALUES (6, 'Ol Dirty Bastard');
INSERT INTO foo VALUES (7, 'Raekwon');
INSERT INTO foo VALUES (8, 'RZA');
INSERT INTO foo VALUES (9, 'U-God');
INSERT INTO foo VALUES (10, NULL);

SELECT COUNT(id) FROM foo;

SELECT UPPER(val) FROM foo WHERE id = 0;
SELECT UPPER(val) FROM foo WHERE val IS NULL;
SELECT LOWER(val) FROM foo WHERE id = 1;
SELECT LOWER(val) FROM foo WHERE val IS NULL;

SELECT CONCAT(UPPER(val), LOWER(val)) FROM foo WHERE val IS NOT NULL;
SELECT CONCAT(UPPER(val), LOWER(val)) FROM foo WHERE val IS NULL;